### ISSUE TITLE
wordwrap for text viewer

### ISSUE THREAD

**Issue by LifeCANvs** [popcar2/GodotOS#17]
Hi. Nice work on GodotOS so far! May I suggest that you add a wordwrap option for long lines of text to wrap around and be visible without scrolling to the right?

**Comment by HVukman** [comment]
Could this be done with a popup menu in the editor? This is an easy option to set.

**Comment by popcar2** [comment]
Fixed by b7f507b. I've cleaned up the popup menu a bit and added an option for word wrap (which is now enabled by default). Will come in the next update. 

![image](https://github.com/popcar2/GodotOS/assets/16920817/daccce32-fc47-48cc-8c9b-a2dd12f97d08)
