### ISSUE TITLE
Duplicate files are not overwritten

### ISSUE THREAD

**Issue by LinuxUserGD** [popcar2/GodotOS#3]
Steps to reproduce:
- Copy file
- Paste file
- File in folder is duplicated instead

![GodotOS](https://github.com/popcar2/GodotOS/assets/34406967/6b056d5a-4761-46fa-a68c-0481f36ce5b9)

**Comment by popcar2** [comment]
Fixed in the newest commit. Build will likely come later after more changes. Thanks!
